version: "3.8"

services:
  backend:
    build:
      context: ./backend
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    command:
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./env-dev/backend.env
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine3.18
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - ./env-dev/db.env

volumes:
  dev-db-data: