version: "3.8"

services:
  backend:
    build:
      context: ./backend
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    command:
      sh -c " echo 'Waiting for db...' &&
              wait-for-it --service db:5432
              -- echo 'db is ready.' &&
              python manage.py migrate
              "
    env_file:
      - ./env-dev/backend.env
    depends_on:
      - "db"

  db:
    image: postgres:16.1-bookworm
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - ./env-dev/db.env

volumes:
  dev-db-data: