version: "3.8"

services:
  backend:
    build:
      context: ./backend
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
      - dev-static-data:/vol/web
    command:
      sh -c " echo 'Waiting for db...' &&
              wait-for-it --service db:5432
              -- echo 'db is ready.' &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./env-dev/backend.env
    depends_on:
      - "db"

  db:
    image: postgres:16.1-bookworm
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - ./env-dev/db.env

  frontend:
    build:
      context: ./frontend
      args:
        - DEV=true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/app:/app
    command:
      sh -c "npm run dev -- --host=0.0.0.0 --port 5173"

volumes:
  dev-db-data:
  dev-static-data: