# Generated by Django 4.2.8 on 2024-01-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0002_rename_mealplanpreferences_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='cooking_per_week',
            new_name='cookings_per_week',
        ),
    ]
