# Generated by Django 4.2.8 on 2024-01-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipe_recipe_type'),
        ('meal_plan', '0003_rename_cooking_per_week_preferences_cookings_per_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('main_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_dish', to='recipe.recipe')),
                ('salad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salad', to='recipe.recipe')),
                ('side_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_dish', to='recipe.recipe')),
            ],
        ),
    ]
