# Generated by Django 4.2.8 on 2024-01-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0004_meal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
