# Generated by Django 4.2.8 on 2024-01-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0006_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='servings_per_meal',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='servings_per_week',
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
