# Generated by Django 4.2.8 on 2024-01-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0007_mealplan_servings_per_meal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
