# Generated by Django 4.2.8 on 2024-01-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0009_mealplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='servings_per_week',
        ),
        migrations.AddField(
            model_name='preferences',
            name='servings_per_meal',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='cookings_per_week',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
