# Generated by Django 4.2.9 on 2024-01-14 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipe_recipe_type'),
        ('meal_plan', '0010_remove_preferences_servings_per_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='main_dish',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_dish', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='salad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salad', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='side_dish',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side_dish', to='recipe.recipe'),
        ),
    ]
