# Generated by Django 4.2.9 on 2024-01-21 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0012_alter_mealplan_creation_date_alter_preferences_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='meals',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
