# Generated by Django 4.2.9 on 2024-01-21 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipe_recipe_type'),
        ('meal_plan', '0013_remove_mealplan_meals_delete_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('main_dish', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_dish', to='recipe.recipe')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_plan.mealplan')),
                ('salad', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salad', to='recipe.recipe')),
                ('side_dish', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side_dish', to='recipe.recipe')),
            ],
        ),
    ]
