# Generated by Django 4.2.9 on 2024-01-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0014_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_subtracted',
            field=models.BooleanField(default=False),
        ),
    ]
