# Generated by Django 4.2.9 on 2024-01-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0015_meal_is_subtracted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='is_subtracted',
            new_name='is_subtracted_pantry',
        ),
        migrations.AddField(
            model_name='meal',
            name='is_added_shopping_list',
            field=models.BooleanField(default=False),
        ),
    ]
