# Generated by Django 4.2.8 on 2024-01-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0004_recipeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinpantry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
