# Generated by Django 4.2.9 on 2024-01-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0005_alter_ingredientinpantry_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientinpantry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ingredientinpantry',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientinpantry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientInPantry',
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
