# Generated by Django 4.2.9 on 2024-01-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinpantry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
