# Generated by Django 4.2.9 on 2024-01-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0008_alter_ingredientinpantry_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='display_unit',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='measurement_unit',
            field=models.CharField(choices=[('g', 'gram'), ('ml', 'milliliter'), ('un', 'unit')], default='un', max_length=3),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddConstraint(
            model_name='shoppinglistitem',
            constraint=models.UniqueConstraint(fields=('user', 'ingredient'), name='unique_shopping_list_item'),
        ),
    ]
