# Generated by Django 4.2.11 on 2024-07-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0010_alter_recipeingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinpantry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
