# Generated by Django 4.2.8 on 2023-12-18 00:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('directions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=1023), size=None)),
                ('description', models.TextField(blank=True)),
                ('servings', models.PositiveSmallIntegerField(default=None, null=True)),
                ('time_minutes', models.PositiveSmallIntegerField(default=None, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(to='recipe.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
