# Generated by Django 4.2.8 on 2023-12-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipeingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
