name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  
jobs:
  test-lint:
    name: Testing and Linting
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker-compose run --rm backend sh -c "wait-for-it --service db:5432 -- python manage.py test"
      - name: Lint
        run: docker-compose run --rm backend sh -c "flake8"